/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.lambdasawa.yamltesting;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;

import java.io.File;
import java.io.IOException;
import java.util.Map;

public class App {
    public static void main(String[] args) {
        ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
        File yamlFile = new File(args[0]);
        Map<String, Object> data = null;
        try {
            data = mapper.readValue(yamlFile, Map.class);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        System.out.println(data);
    }
}