/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.lambdasawa.yamltesting;

import org.yaml.snakeyaml.Yaml;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Map;

public class App {
    public static void main(String[] args) {
        Yaml yaml = new Yaml();
        try (InputStream in = Files.newInputStream(Paths.get(args[0]))) {
            Map<String, Object> obj = yaml.load(in);
            System.out.println(obj);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}